#!/usr/bin/env bash
# openclaw-bootstrap — manifest-driven reconciler that runs on every container start.
#
# Responsibilities (in order):
#   1. Snapshot critical /data state (one tar.gz per deploy, prune old ones).
#   2. Reconcile wrappers and symlinks from /app/manifest.json.
#   3. Prune accumulated *.bak clutter.
#   4. Assert required binaries, files, and openclaw.json shape — fail fast if any missing.
#   5. Write a single-file health report to /data/.openclaw/bootstrap.last.json.
#   6. exec "$@" — hand off to node src/server.js with no extra process layer.
#
# Designed to be idempotent: running it 1000 times produces the same state.

set -uo pipefail

MANIFEST="${OPENCLAW_MANIFEST:-/app/manifest.json}"
STATE_DIR="/data/.openclaw"
BIN_DIR="${STATE_DIR}/bin"
SNAPSHOT_DIR="/data/snapshots"
LAST_REPORT="${STATE_DIR}/bootstrap.last.json"
LOG="${STATE_DIR}/bootstrap.log"
COMMIT="${RAILWAY_GIT_COMMIT_SHA:-unknown}"
DEPLOY_ID="${RAILWAY_DEPLOYMENT_ID:-unknown}"

mkdir -p "$STATE_DIR" "$BIN_DIR" "$SNAPSHOT_DIR"
exec > >(tee -a "$LOG") 2>&1

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { printf '[bootstrap %s] %s\n' "$(ts)" "$*"; }

actions=()
warnings=()
errors=()

write_report() {
  local status="$1" detail="${2:-}"
  jq -n \
    --arg ts "$(ts)" \
    --arg commit "$COMMIT" \
    --arg deploy "$DEPLOY_ID" \
    --arg status "$status" \
    --arg detail "$detail" \
    --argjson actions  "$(printf '%s\n' "${actions[@]:-}"  | jq -R . | jq -s 'map(select(. != ""))')" \
    --argjson warnings "$(printf '%s\n' "${warnings[@]:-}" | jq -R . | jq -s 'map(select(. != ""))')" \
    --argjson errors   "$(printf '%s\n' "${errors[@]:-}"   | jq -R . | jq -s 'map(select(. != ""))')" \
    '{ts:$ts, commit:$commit, deploy:$deploy, status:$status, detail:$detail,
      actions:$actions, warnings:$warnings, errors:$errors}' \
    > "$LAST_REPORT" 2>/dev/null || true
}

die() {
  log "FATAL: $*"
  errors+=("FATAL: $*")
  write_report "fail" "$*"
  exit 1
}

log "starting commit=$COMMIT deploy=$DEPLOY_ID"

[ -f "$MANIFEST" ] || die "manifest not found at $MANIFEST"
command -v jq >/dev/null || die "jq missing — Dockerfile must install jq"

# ---------------------------------------------------------------------------
# 1. Snapshot critical state (idempotent: one tarball per commit)
# ---------------------------------------------------------------------------
KEEP=$(jq -r '.snapshot.keep_last // 10' "$MANIFEST")
SNAP="${SNAPSHOT_DIR}/preboot-${COMMIT}.tar.gz"
if [ ! -f "$SNAP" ]; then
  mapfile -t snap_paths < <(jq -r '.snapshot.paths[]?' "$MANIFEST")
  existing=()
  for p in "${snap_paths[@]}"; do [ -e "$p" ] && existing+=("$p"); done
  if [ "${#existing[@]}" -gt 0 ]; then
    if tar -czf "$SNAP" "${existing[@]}" 2>/dev/null; then
      sz=$(du -h "$SNAP" | cut -f1)
      actions+=("snapshot: $SNAP ($sz, ${#existing[@]} paths)")
      log "snapshot: $SNAP ($sz)"
    else
      warnings+=("snapshot failed for commit $COMMIT")
    fi
  else
    warnings+=("no snapshot paths exist yet — first boot?")
  fi
  ls -1t "$SNAPSHOT_DIR"/preboot-*.tar.gz 2>/dev/null | tail -n "+$((KEEP+1))" | xargs -r rm -f
fi

# ---------------------------------------------------------------------------
# 2. Reconcile wrappers (write idempotently to /data/.openclaw/bin)
# ---------------------------------------------------------------------------
reconcile_wrapper() {
  local name target interp env_block args_block tmp dest
  name="$1"
  local spec
  spec=$(jq -c --arg n "$name" '.wrappers[] | select(.name==$n)' "$MANIFEST")
  target=$(echo "$spec" | jq -r '.target')
  interp=$(echo "$spec" | jq -r '.interpreter // ""')

  env_block=$(echo "$spec" | jq -r '
    (.env // {}) | to_entries[] |
    "export \(.key)=\"\(.value)\""
  ')
  args_block=$(echo "$spec" | jq -r '
    (.args // []) | map(@sh) | join(" ")
  ')

  dest="${BIN_DIR}/${name}"
  tmp="${BIN_DIR}/.${name}.tmp"
  {
    echo "#!/usr/bin/env bash"
    echo "# Generated by openclaw-bootstrap from $MANIFEST. DO NOT EDIT."
    [ -n "$env_block" ] && echo "$env_block"
    if [ -n "$interp" ]; then
      echo "exec $interp \"$target\" $args_block \"\$@\""
    else
      echo "exec \"$target\" $args_block \"\$@\""
    fi
  } > "$tmp"
  chmod +x "$tmp"

  if ! cmp -s "$tmp" "$dest" 2>/dev/null; then
    mv "$tmp" "$dest"
    actions+=("wrapper: $name -> $target")
    log "wrapper: $name -> $target"
  else
    rm -f "$tmp"
  fi
}

while read -r name; do
  [ -z "$name" ] && continue
  reconcile_wrapper "$name" || warnings+=("wrapper failed: $name")
done < <(jq -r '.wrappers[].name' "$MANIFEST")

# ---------------------------------------------------------------------------
# 3. Reconcile symlinks
# ---------------------------------------------------------------------------
while read -r link; do
  [ -z "$link" ] && continue
  from=$(echo "$link" | jq -r '.from')
  to=$(echo   "$link" | jq -r '.to')
  mkdir -p "$(dirname "$from")"
  if [ -L "$from" ] && [ "$(readlink "$from")" = "$to" ]; then
    continue
  fi
  rm -rf "$from"
  ln -s "$to" "$from"
  actions+=("symlink: $from -> $to")
  log "symlink: $from -> $to"
done < <(jq -c '.symlinks[]?' "$MANIFEST")

# ---------------------------------------------------------------------------
# 4. Maintenance: prune *.bak clutter
# ---------------------------------------------------------------------------
prune_pattern=$(jq -r '.maintenance.prune_backups.pattern // empty' "$MANIFEST")
prune_keep=$(jq -r '.maintenance.prune_backups.keep // 3' "$MANIFEST")
if [ -n "$prune_pattern" ]; then
  # shellcheck disable=SC2086
  pruned=$(ls -1t $prune_pattern 2>/dev/null | tail -n "+$((prune_keep+1))" | wc -l)
  if [ "$pruned" -gt 0 ]; then
    # shellcheck disable=SC2086
    ls -1t $prune_pattern 2>/dev/null | tail -n "+$((prune_keep+1))" | xargs -r rm -f
    actions+=("pruned $pruned old backup file(s)")
    log "pruned $pruned old backup(s) matching $prune_pattern"
  fi
fi

# ---------------------------------------------------------------------------
# 5. Assertions — fail loud if anything's missing
# ---------------------------------------------------------------------------
missing_bins=()
while read -r b; do
  [ -z "$b" ] && continue
  command -v "$b" >/dev/null 2>&1 || missing_bins+=("$b")
done < <(jq -r '.assertions.required_binaries[]?' "$MANIFEST")

missing_files=()
while read -r f; do
  [ -z "$f" ] && continue
  [ -e "$f" ] || missing_files+=("$f")
done < <(jq -r '.assertions.required_files[]?' "$MANIFEST")

cfg_errors=()
if [ -f /data/.openclaw/openclaw.json ]; then
  expected_min=$(jq -r '.assertions.openclaw_config.min_agents // 0' "$MANIFEST")
  actual_agents=$(jq -r '.agents.list | length' /data/.openclaw/openclaw.json 2>/dev/null || echo 0)
  if [ "$actual_agents" -lt "$expected_min" ]; then
    cfg_errors+=("agent count $actual_agents < expected $expected_min")
  fi

  while read -r required_id; do
    [ -z "$required_id" ] && continue
    if ! jq -e --arg id "$required_id" '.agents.list[] | select(.id==$id)' \
         /data/.openclaw/openclaw.json >/dev/null 2>&1; then
      cfg_errors+=("missing agent: $required_id")
    fi
  done < <(jq -r '.assertions.openclaw_config.required_agent_ids[]?' "$MANIFEST")

  while read -r ch; do
    [ -z "$ch" ] && continue
    if ! jq -e --arg c "$ch" '.channels[$c]' /data/.openclaw/openclaw.json >/dev/null 2>&1; then
      cfg_errors+=("missing channel: $ch")
    fi
  done < <(jq -r '.assertions.openclaw_config.required_channels[]?' "$MANIFEST")
fi

if [ "${#missing_bins[@]}" -gt 0 ];   then errors+=("missing binaries: ${missing_bins[*]}"); fi
if [ "${#missing_files[@]}" -gt 0 ];  then errors+=("missing files: ${missing_files[*]}"); fi
if [ "${#cfg_errors[@]}" -gt 0 ];     then errors+=("config errors: ${cfg_errors[*]}"); fi

if [ "${#errors[@]}" -gt 0 ]; then
  for e in "${errors[@]}"; do log "ERROR: $e"; done
  log "PATH=$PATH"
  write_report "fail" "${#errors[@]} fatal error(s)"
  exit 1
fi

write_report "ok"
log "reconcile complete: ${#actions[@]} action(s), ${#warnings[@]} warning(s), 0 error(s)"

# ---------------------------------------------------------------------------
# 6. Hand off to the app (tini stays as PID 1)
# ---------------------------------------------------------------------------
exec "$@"
