#!/usr/bin/env bash
# openclaw-bootstrap — manifest-driven reconciler that runs on every container start.
#
# Responsibilities (in order):
#   1. Snapshot critical /data state (one tar.gz per deploy, prune old ones).
#   2. Reconcile wrappers and symlinks from /app/manifest.json.
#   3. Prune accumulated *.bak clutter.
#   4. Assert required binaries, files, and openclaw.json shape — fail fast if any missing.
#   5. Write a single-file health report to /data/.openclaw/bootstrap.last.json.
#   6. exec "$@" — hand off to node src/server.js with no extra process layer.
#
# Designed to be idempotent: running it 1000 times produces the same state.

set -uo pipefail

MANIFEST="${OPENCLAW_MANIFEST:-/app/manifest.json}"
STATE_DIR="/data/.openclaw"
BIN_DIR="${STATE_DIR}/bin"
SNAPSHOT_DIR="/data/snapshots"
LAST_REPORT="${STATE_DIR}/bootstrap.last.json"
LOG="${STATE_DIR}/bootstrap.log"
COMMIT="${RAILWAY_GIT_COMMIT_SHA:-unknown}"
DEPLOY_ID="${RAILWAY_DEPLOYMENT_ID:-unknown}"

mkdir -p "$STATE_DIR" "$BIN_DIR" "$SNAPSHOT_DIR"
exec > >(tee -a "$LOG") 2>&1

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { printf '[bootstrap %s] %s\n' "$(ts)" "$*"; }

actions=()
warnings=()
errors=()

write_report() {
  local status="$1" detail="${2:-}"
  jq -n \
    --arg ts "$(ts)" \
    --arg commit "$COMMIT" \
    --arg deploy "$DEPLOY_ID" \
    --arg status "$status" \
    --arg detail "$detail" \
    --argjson actions  "$(printf '%s\n' "${actions[@]:-}"  | jq -R . | jq -s 'map(select(. != ""))')" \
    --argjson warnings "$(printf '%s\n' "${warnings[@]:-}" | jq -R . | jq -s 'map(select(. != ""))')" \
    --argjson errors   "$(printf '%s\n' "${errors[@]:-}"   | jq -R . | jq -s 'map(select(. != ""))')" \
    '{ts:$ts, commit:$commit, deploy:$deploy, status:$status, detail:$detail,
      actions:$actions, warnings:$warnings, errors:$errors}' \
    > "$LAST_REPORT" 2>/dev/null || true
}

die() {
  log "FATAL: $*"
  errors+=("FATAL: $*")
  write_report "fail" "$*"
  exit 1
}

log "starting commit=$COMMIT deploy=$DEPLOY_ID"

[ -f "$MANIFEST" ] || die "manifest not found at $MANIFEST"
command -v jq >/dev/null || die "jq missing — Dockerfile must install jq"

# ---------------------------------------------------------------------------
# 1. Snapshot critical state (idempotent: one tarball per commit)
# ---------------------------------------------------------------------------
KEEP=$(jq -r '.snapshot.keep_last // 10' "$MANIFEST")
SNAP="${SNAPSHOT_DIR}/preboot-${COMMIT}.tar.gz"
if [ ! -f "$SNAP" ]; then
  mapfile -t snap_paths < <(jq -r '.snapshot.paths[]?' "$MANIFEST")
  existing=()
  for p in "${snap_paths[@]}"; do
    # Manifest paths may contain globs (e.g. /data/workspace-*/skills) so that
    # per-agent workspaces are captured without listing every agent by hand.
    # Unquoted expansion is intentional; these paths never contain spaces.
    # shellcheck disable=SC2086
    for m in $p; do [ -e "$m" ] && existing+=("$m"); done
  done
  if [ "${#existing[@]}" -gt 0 ]; then
    if tar -czf "$SNAP" "${existing[@]}" 2>/dev/null; then
      sz=$(du -h "$SNAP" | cut -f1)
      actions+=("snapshot: $SNAP ($sz, ${#existing[@]} paths)")
      log "snapshot: $SNAP ($sz)"
    else
      warnings+=("snapshot failed for commit $COMMIT")
    fi
  else
    warnings+=("no snapshot paths exist yet — first boot?")
  fi
  ls -1t "$SNAPSHOT_DIR"/preboot-*.tar.gz 2>/dev/null | tail -n "+$((KEEP+1))" | xargs -r rm -f
fi

# ---------------------------------------------------------------------------
# 2. Reconcile wrappers (write idempotently to /data/.openclaw/bin)
# ---------------------------------------------------------------------------
reconcile_wrapper() {
  local name target interp env_block args_block tmp dest
  name="$1"
  local spec
  spec=$(jq -c --arg n "$name" '.wrappers[] | select(.name==$n)' "$MANIFEST")
  target=$(echo "$spec" | jq -r '.target')
  interp=$(echo "$spec" | jq -r '.interpreter // ""')

  env_block=$(echo "$spec" | jq -r '
    (.env // {}) | to_entries[] |
    "export \(.key)=\"\(.value)\""
  ')
  args_block=$(echo "$spec" | jq -r '
    (.args // []) | map(@sh) | join(" ")
  ')

  dest="${BIN_DIR}/${name}"
  tmp="${BIN_DIR}/.${name}.tmp"
  {
    echo "#!/usr/bin/env bash"
    echo "# Generated by openclaw-bootstrap from $MANIFEST. DO NOT EDIT."
    [ -n "$env_block" ] && echo "$env_block"
    if [ -n "$interp" ]; then
      echo "exec $interp \"$target\" $args_block \"\$@\""
    else
      echo "exec \"$target\" $args_block \"\$@\""
    fi
  } > "$tmp"
  chmod +x "$tmp"

  if ! cmp -s "$tmp" "$dest" 2>/dev/null; then
    mv "$tmp" "$dest"
    actions+=("wrapper: $name -> $target")
    log "wrapper: $name -> $target"
  else
    rm -f "$tmp"
  fi
}

while read -r name; do
  [ -z "$name" ] && continue
  reconcile_wrapper "$name" || warnings+=("wrapper failed: $name")
done < <(jq -r '.wrappers[].name' "$MANIFEST")

# ---------------------------------------------------------------------------
# 3. Reconcile symlinks
# ---------------------------------------------------------------------------
while read -r link; do
  [ -z "$link" ] && continue
  from=$(echo "$link" | jq -r '.from')
  to=$(echo   "$link" | jq -r '.to')
  mkdir -p "$(dirname "$from")"
  if [ -L "$from" ] && [ "$(readlink "$from")" = "$to" ]; then
    continue
  fi
  rm -rf "$from"
  ln -s "$to" "$from"
  actions+=("symlink: $from -> $to")
  log "symlink: $from -> $to"
done < <(jq -c '.symlinks[]?' "$MANIFEST")

# ---------------------------------------------------------------------------
# 4. Reconcile provisioned payloads (image -> /data)
#
# Anything declared in .provisioned is restored from the image on every boot.
# This is what makes a runtime capability (e.g. the Shopify layer) survive a
# redeploy, an OpenClaw upgrade that rewrites workspaces, or a lost volume.
#
# Invariant preserved: this NEVER writes openclaw.json. Config remains
# runtime-owned; we only assert on it further down.
# ---------------------------------------------------------------------------
CFG=/data/.openclaw/openclaw.json

# 2026.8.1 moved the roster from agents.list (array) to agents.entries (object
# keyed by agent id); openclaw doctor migrates it, and config validate warns
# until it does. Both shapes are live in the wild, so every read of the roster
# goes through this jq helper, which normalises either one to an array of agent
# objects carrying .id. Without it the assertions below see zero agents after a
# migration and fail the deploy fatally — crash-looping a perfectly good box.
JQ_AGENTS='def agent_list: if ((.agents.entries? | type) == "object")
  then (.agents.entries | to_entries | map(.value + {id: .key}))
  else (.agents.list // []) end; '

# Resolve an agent's workspace, honouring the agents.defaults.workspace
# fallback (that is how "main" resolves to /data/workspace).
agent_workspace() {
  local id="$1"
  [ -f "$CFG" ] || return 1
  jq -r --arg id "$id" "$JQ_AGENTS"'
    (.agents.defaults.workspace // "/data/workspace") as $def
    | (agent_list[]? | select(.id==$id) | (.workspace // .cwd // $def))
  ' "$CFG" 2>/dev/null | head -1
}

while read -r prov; do
  [ -z "$prov" ] && continue
  pname=$(echo "$prov" | jq -r '.name')

  # -- directories (created before files land in them)
  while read -r d; do
    [ -z "$d" ] && continue
    dpath=$(echo "$d" | jq -r '.path'); dmode=$(echo "$d" | jq -r '.mode // "755"')
    mkdir -p "$dpath" && chmod "$dmode" "$dpath"
  done < <(echo "$prov" | jq -c '.ensure_dirs[]?')

  # -- binaries (copy only when content differs, so boots stay quiet)
  while read -r b; do
    [ -z "$b" ] && continue
    bsrc=$(echo "$b" | jq -r '.src'); bdest=$(echo "$b" | jq -r '.dest')
    bmode=$(echo "$b" | jq -r '.mode // "755"')
    if [ ! -f "$bsrc" ]; then
      warnings+=("provision $pname: payload missing in image: $bsrc"); continue
    fi
    mkdir -p "$(dirname "$bdest")"
    if ! cmp -s "$bsrc" "$bdest" 2>/dev/null; then
      install -m "$bmode" "$bsrc" "$bdest"
      actions+=("provision $pname: $bdest")
      log "provision $pname: installed $bdest"
    fi
  done < <(echo "$prov" | jq -c '.binaries[]?')

  # -- seed files (only when absent; never clobber live runtime state)
  while read -r s; do
    [ -z "$s" ] && continue
    ssrc=$(echo "$s" | jq -r '.src'); sdest=$(echo "$s" | jq -r '.dest')
    smode=$(echo "$s" | jq -r '.mode // "600"')
    if [ -f "$ssrc" ] && [ ! -e "$sdest" ]; then
      mkdir -p "$(dirname "$sdest")"
      install -m "$smode" "$ssrc" "$sdest"
      actions+=("provision $pname: seeded $sdest")
      log "provision $pname: seeded $sdest"
    fi
  done < <(echo "$prov" | jq -c '.seed_files[]?')

  # -- skill, copied into each target agent's own workspace
  skill_src=$(echo "$prov" | jq -r '.agent_skill.src // empty')
  skill_name=$(echo "$prov" | jq -r '.agent_skill.skill_name // empty')
  if [ -n "$skill_src" ] && [ -n "$skill_name" ]; then
    if [ ! -d "$skill_src" ]; then
      warnings+=("provision $pname: skill payload missing in image: $skill_src")
    else
      while read -r aid; do
        [ -z "$aid" ] && continue
        ws=$(agent_workspace "$aid")
        if [ -z "$ws" ] || [ "$ws" = "null" ]; then
          warnings+=("provision $pname: no workspace for agent $aid"); continue
        fi
        dest="${ws}/skills/${skill_name}"
        if ! diff -rq "$skill_src" "$dest" >/dev/null 2>&1; then
          mkdir -p "$dest"
          cp -R "$skill_src/." "$dest/"
          actions+=("provision $pname: skill -> $dest")
          log "provision $pname: skill -> $dest"
        fi
        # The skill is useless unless the agent lists it. We do not write config,
        # so surface the drift instead.
        if ! jq -e --arg id "$aid" --arg s "$skill_name" \
             "$JQ_AGENTS"'agent_list[] | select(.id==$id) | .skills // [] | index($s)' \
             "$CFG" >/dev/null 2>&1; then
          warnings+=("agent $aid does not list skill '$skill_name' in openclaw.json")
        fi
      done < <(echo "$prov" | jq -r '.agent_skill.agents[]?')
    fi
  fi

  # -- credentials present? (tokens are never baked into the image)
  if [ "$(echo "$prov" | jq -r '.assert_store_tokens // false')" = "true" ]; then
    reg=/data/.openclaw/credentials/shopify/stores.json
    toks=/data/.openclaw/credentials/shopify/tokens.env
    if [ -f "$reg" ]; then
      while read -r pair; do
        [ -z "$pair" ] && continue
        slug="${pair%%|*}"; envname="${pair##*|}"
        if ! grep -q "^${envname}=" "$toks" 2>/dev/null && [ -z "${!envname:-}" ]; then
          warnings+=("shopify store '$slug' has no token ($envname missing from tokens.env and env)")
        fi
      done < <(jq -r '.stores | to_entries[] |
                 "\(.key)|\(.value.token_env // ("SHOPIFY_TOKEN_" + (.key | ascii_upcase)))"' \
               "$reg" 2>/dev/null)
    fi
  fi

  # -- generic credential check: keys expected in an env-file (or the environment)
  envf=$(echo "$prov" | jq -r '.assert_env_file.path // empty')
  if [ -n "$envf" ]; then
    while read -r k; do
      [ -z "$k" ] && continue
      if ! grep -q "^${k}=." "$envf" 2>/dev/null && [ -z "${!k:-}" ]; then
        warnings+=("provision $pname: $k missing from $envf and the environment")
      fi
    done < <(echo "$prov" | jq -r '.assert_env_file.keys[]?')
  fi
done < <(jq -c '.provisioned[]?' "$MANIFEST")

# ---------------------------------------------------------------------------
# 5. Resolve secrets from 1Password (optional, fail-soft)
#
# Contract, in order of importance:
#   1. Never take the bot down. No path here is fatal.
#   2. Never replace a working secret with a broken one. A value is only written
#      after a successful, non-empty fetch.
#   3. Do nothing at all unless OP_SERVICE_ACCOUNT_TOKEN is set, so this ships
#      safely before the 1Password side exists.
#
# Secrets land in the ordinary places OpenClaw already reads (its .env and the
# usual credential files) — nothing downstream knows 1Password is involved.
# ---------------------------------------------------------------------------
sec_enabled=$(jq -r '.secrets.enabled // false' "$MANIFEST")
if [ "$sec_enabled" = "true" ]; then
  if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]; then
    log "secrets: OP_SERVICE_ACCOUNT_TOKEN not set — skipping (on-disk secrets untouched)"
  elif ! command -v op >/dev/null 2>&1; then
    warnings+=("secrets: op CLI missing from image — skipping")
  else
    sec_ok=0; sec_fail=0

    # Upsert KEY=value in a KEY=value file, preserving other keys and perms.
    upsert_env_line() {
      local file="$1" key="$2" val="$3" mode="${4:-600}" tmp
      tmp="${file}.tmp.$$"
      mkdir -p "$(dirname "$file")"
      { [ -f "$file" ] && grep -v "^${key}=" "$file" 2>/dev/null; printf '%s=%s\n' "$key" "$val"; } > "$tmp"
      chmod "$mode" "$tmp" && mv "$tmp" "$file"
    }

    while read -r item; do
      [ -z "$item" ] && continue
      s_name=$(echo "$item" | jq -r '.name')
      s_ref=$(echo  "$item" | jq -r '.ref')
      s_dest=$(echo "$item" | jq -r '.dest // "env"')
      s_path=$(echo "$item" | jq -r '.path // empty')
      s_mode=$(echo "$item" | jq -r '.mode // "600"')

      # Fetch first, into a variable. Only touch disk on success.
      if ! s_val=$(op read --no-newline "$s_ref" 2>/dev/null) || [ -z "$s_val" ]; then
        warnings+=("secrets: could not read $s_name from 1Password — keeping existing value")
        # Log too: a silent secret failure should be visible in the deploy log,
        # not only in bootstrap.last.json.
        log "secrets: WARN could not read $s_name ($s_ref) — keeping existing value"
        sec_fail=$((sec_fail+1))
        continue
      fi

      case "$s_dest" in
        env)
          upsert_env_line "$(jq -r '.secrets.env_file' "$MANIFEST")" "$s_name" "$s_val" 600 ;;
        env_file)
          [ -n "$s_path" ] || { warnings+=("secrets: $s_name has dest=env_file but no path"); continue; }
          upsert_env_line "$s_path" "$s_name" "$s_val" "$s_mode" ;;
        file)
          [ -n "$s_path" ] || { warnings+=("secrets: $s_name has dest=file but no path"); continue; }
          mkdir -p "$(dirname "$s_path")"
          printf '%s' "$s_val" > "${s_path}.tmp.$$" \
            && chmod "$s_mode" "${s_path}.tmp.$$" && mv "${s_path}.tmp.$$" "$s_path" ;;
        *)
          warnings+=("secrets: $s_name has unknown dest '$s_dest'"); continue ;;
      esac
      unset s_val
      sec_ok=$((sec_ok+1))
    done < <(jq -c '.secrets.items[]?' "$MANIFEST")

    if [ "$sec_ok" -gt 0 ]; then
      actions+=("secrets: resolved $sec_ok from 1Password")
      log "secrets: resolved $sec_ok from 1Password ($sec_fail failed)"
    fi
    [ "$sec_fail" -gt 0 ] && warnings+=("secrets: $sec_fail item(s) failed to resolve — previous values kept")
  fi
fi

# ---------------------------------------------------------------------------
# 6. Maintenance: prune *.bak clutter
# ---------------------------------------------------------------------------
prune_pattern=$(jq -r '.maintenance.prune_backups.pattern // empty' "$MANIFEST")
prune_keep=$(jq -r '.maintenance.prune_backups.keep // 3' "$MANIFEST")
if [ -n "$prune_pattern" ]; then
  # shellcheck disable=SC2086
  pruned=$(ls -1t $prune_pattern 2>/dev/null | tail -n "+$((prune_keep+1))" | wc -l)
  if [ "$pruned" -gt 0 ]; then
    # shellcheck disable=SC2086
    ls -1t $prune_pattern 2>/dev/null | tail -n "+$((prune_keep+1))" | xargs -r rm -f
    actions+=("pruned $pruned old backup file(s)")
    log "pruned $pruned old backup(s) matching $prune_pattern"
  fi
fi

# ---------------------------------------------------------------------------
# 7. Assertions — fail loud if anything's missing
# ---------------------------------------------------------------------------
missing_bins=()
while read -r b; do
  [ -z "$b" ] && continue
  command -v "$b" >/dev/null 2>&1 || missing_bins+=("$b")
done < <(jq -r '.assertions.required_binaries[]?' "$MANIFEST")

missing_files=()
while read -r f; do
  [ -z "$f" ] && continue
  [ -e "$f" ] || missing_files+=("$f")
done < <(jq -r '.assertions.required_files[]?' "$MANIFEST")

cfg_errors=()
if [ -f /data/.openclaw/openclaw.json ]; then
  expected_min=$(jq -r '.assertions.openclaw_config.min_agents // 0' "$MANIFEST")
  actual_agents=$(jq -r "$JQ_AGENTS"'agent_list | length' /data/.openclaw/openclaw.json 2>/dev/null || echo 0)
  if [ "$actual_agents" -lt "$expected_min" ]; then
    cfg_errors+=("agent count $actual_agents < expected $expected_min")
  fi

  while read -r required_id; do
    [ -z "$required_id" ] && continue
    if ! jq -e --arg id "$required_id" "$JQ_AGENTS"'agent_list[] | select(.id==$id)' \
         /data/.openclaw/openclaw.json >/dev/null 2>&1; then
      cfg_errors+=("missing agent: $required_id")
    fi
  done < <(jq -r '.assertions.openclaw_config.required_agent_ids[]?' "$MANIFEST")

  while read -r ch; do
    [ -z "$ch" ] && continue
    if ! jq -e --arg c "$ch" '.channels[$c]' /data/.openclaw/openclaw.json >/dev/null 2>&1; then
      cfg_errors+=("missing channel: $ch")
    fi
  done < <(jq -r '.assertions.openclaw_config.required_channels[]?' "$MANIFEST")
fi

if [ "${#missing_bins[@]}" -gt 0 ];   then errors+=("missing binaries: ${missing_bins[*]}"); fi
# Missing runtime files are NON-FATAL: OpenClaw upgrades can migrate state files
# (e.g. cron/jobs.json, devices/paired.json) into its SQLite state DB, and a stale
# assertion must not crash-loop the whole bot. Warn instead of failing the boot.
if [ "${#missing_files[@]}" -gt 0 ];  then warnings+=("missing files (non-fatal, may be migrated into state DB): ${missing_files[*]}"); fi
if [ "${#cfg_errors[@]}" -gt 0 ];     then errors+=("config errors: ${cfg_errors[*]}"); fi

if [ "${#errors[@]}" -gt 0 ]; then
  for e in "${errors[@]}"; do log "ERROR: $e"; done
  log "PATH=$PATH"
  write_report "fail" "${#errors[@]} fatal error(s)"
  exit 1
fi

write_report "ok"
log "reconcile complete: ${#actions[@]} action(s), ${#warnings[@]} warning(s), 0 error(s)"

# ---------------------------------------------------------------------------
# 8. Hand off to the app (tini stays as PID 1)
# ---------------------------------------------------------------------------
exec "$@"
